# Use the existing image as the base
FROM autogen_dev_img

# Copy your files into the container
COPY test.py test.py
COPY test_openai.py test_openai.py

# Additional instructions for your Dockerfile
RUN pip install --force-reinstall autogen
RUN pip install --force-reinstall pyautogen

# Command to run when the container starts
CMD ["/bin/bash"]